version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Hello, CodeBuild!"
      - ls
      - node --version
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - rm -r -f node_modules
      - ls
artifacts:
  files:
    - frontend/**/*
